Algoritmo "ALG1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/10/2022
Var
// Seção de Declarações das variáveis 
  nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  nota <- 100
  escreva("a nota é:", nota)

Fimalgoritmo