Algoritmo "variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cleiton Melo
// Descrição   : Declaração de variáveis
// Autor(a)    : Malcolm Souza Felix
// Data atual  : 04/10/2022
Var
// Seção de Declarações das variáveis 

   primeiroNome, segundoNome, cidade, endereco: caractere
   idade: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo